services:
  php:
    image: php:8.3.17-apache
    container_name: php83
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.6-noble
    restart: always
    ports:
      - "8090:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
