services:
  php:
    image: php:8.3.17-apache
    container_name: php83
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mysql-burgos.alwaysdata.net
      DB_DATABASE: burgos_ecoride
      DB_USER: burgos
      DB_PASSWORD: Is@bel1410
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-burgos.alwaysdata.net
      PMA_PORT: 3306
      PMA_USER: burgos
      PMA_PASSWORD: Is@bel1410

  mongodb:
    image: mongo:8.0.6-noble
    restart: always
    ports:
      - "8090:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_ecoride
      MONGO_INITDB_ROOT_PASSWORD: Is@bel1410
